{% set name = "imy" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imy-{{ version }}.tar.gz
  sha256: d8c2639bc3e82786ad48b257b8308ee5fc36fd1fc90d96907dc8b95ccaefb26a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.10.0,<4.0.0
    - json5 <0.10.0,>=0.9.22
    - motor <4.0.0,>=3.3.2
    - uniserde <0.4.0,>=0.3.13
    - introspection <2.0.0,>=1.8.0
  run_constrained:
    - json5 >=0.9.22,<0.10.0
    - motor >=3.3.2,<4.0.0
    - uniserde >=0.3.13,<0.4.0
    - introspection >=1.8.0,<2.0.0

test:
  imports:
    - imy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/mad-moo/i-miss-you
  summary: Convenience utilities for Python projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
