{% set name = "imy" %}
{% set version = "0.7.0.post0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imy-{{ version }}.tar.gz
  sha256: a6b55788ac7dd81184dbf1d9fb173a46be385445ed1e7b14e31586a2e949788c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling ==1.26.3
    - pip
  run:
    - python >={{ python_min }}
    - typing_extensions
  run_constrained:
    - json5 >=0.9.22
    - uniserde >=0.3.14
    - introspection >=1.9.1

test:
  imports:
    - imy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/mad-moo/i-miss-you
  summary: Convenience utilities for Python projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
