{% set name = "imy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imy-{{ version }}.tar.gz
  sha256: e1bb10d280e27ab9d0291643fe33903e23cfb402227bd733706db78ff0a10030

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10.0
  run_constrained:
    - json5 >=0.9.22
    - uniserde >=0.3.14
    - introspection >=1.9.1

test:
  imports:
    - imy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/mad-moo/i-miss-you
  summary: Convenience utilities for Python projects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
